# Generated by Django 6.0.7 on 2026-07-20 20:40

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("VEHICLE", "Vehículo"), ("PROPERTY", "Inmueble")],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("price_cop", models.DecimalField(decimal_places=2, max_digits=15)),
                ("city", models.CharField(max_length=100)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Disponible"),
                            ("RESERVED", "Reservado"),
                            ("SOLD", "Vendido"),
                            ("INACTIVE", "Inactivo"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("views_count", models.IntegerField(default=0)),
                ("unlock_count", models.IntegerField(default=0)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "inventory_items",
            },
        ),
        migrations.CreateModel(
            name="PropertyItem",
            fields=[
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="property",
                        serialize=False,
                        to="inventory.inventoryitem",
                    ),
                ),
                ("property_type", models.CharField(max_length=20)),
                ("neighborhood", models.CharField(blank=True, max_length=120)),
                ("area_sqm", models.IntegerField(blank=True, null=True)),
                ("bedrooms", models.IntegerField(blank=True, null=True)),
                ("bathrooms", models.IntegerField(blank=True, null=True)),
                ("parking_spots", models.IntegerField(blank=True, null=True)),
                ("floor", models.IntegerField(blank=True, null=True)),
                ("has_elevator", models.BooleanField(blank=True, null=True)),
                ("has_pool", models.BooleanField(blank=True, null=True)),
                ("has_sports_courts", models.BooleanField(blank=True, null=True)),
                ("has_social_area", models.BooleanField(blank=True, null=True)),
                ("has_terrace", models.BooleanField(blank=True, null=True)),
                ("urbanization_type", models.CharField(blank=True, max_length=30)),
                ("construction_year", models.IntegerField(blank=True, null=True)),
                ("socioeconomic_stratum", models.IntegerField(blank=True, null=True)),
                (
                    "admin_fee_cop",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "utilities_avg_cop",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("available_utilities", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "inventory_properties",
            },
        ),
        migrations.CreateModel(
            name="VehicleItem",
            fields=[
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="vehicle",
                        serialize=False,
                        to="inventory.inventoryitem",
                    ),
                ),
                ("brand", models.CharField(max_length=80)),
                ("model", models.CharField(max_length=80)),
                ("line", models.CharField(blank=True, max_length=120)),
                ("year", models.IntegerField()),
                ("fuel_type", models.CharField(blank=True, max_length=30)),
                ("body_type", models.CharField(blank=True, max_length=30)),
                ("traction", models.CharField(blank=True, max_length=10)),
                ("transmission", models.CharField(blank=True, max_length=20)),
                ("mileage_km", models.IntegerField()),
                ("doors", models.IntegerField(blank=True, null=True)),
                ("single_owner", models.BooleanField(blank=True, null=True)),
                ("plate_last_digit", models.CharField(blank=True, max_length=2)),
                ("accessories", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "inventory_vehicles",
            },
        ),
        migrations.CreateModel(
            name="InventoryImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image_url", models.URLField(max_length=500)),
                ("is_ai_generated", models.BooleanField(default=False)),
                ("source_prompt", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_images",
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["seller", "status"], name="inventory_i_seller__a95b2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["asset_type", "status"], name="inventory_i_asset_t_9c04c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(fields=["city"], name="inventory_i_city_5e9cc6_idx"),
        ),
    ]
