# Generated by Django 6.0.7 on 2026-07-24 03:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventoryimage",
            options={
                "ordering": ["order"],
                "verbose_name": "Foto de la publicación",
                "verbose_name_plural": "Fotos de la publicación",
            },
        ),
        migrations.AlterModelOptions(
            name="inventoryitem",
            options={
                "verbose_name": "Publicación",
                "verbose_name_plural": "Publicaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="propertyitem",
            options={
                "verbose_name": "Datos del inmueble",
                "verbose_name_plural": "Datos de inmuebles",
            },
        ),
        migrations.AlterModelOptions(
            name="vehicleitem",
            options={
                "verbose_name": "Datos del vehículo",
                "verbose_name_plural": "Datos de vehículos",
            },
        ),
        migrations.AddField(
            model_name="vehicleitem",
            name="color",
            field=models.CharField(blank=True, max_length=40, verbose_name="Color"),
        ),
        migrations.AddField(
            model_name="vehicleitem",
            name="engine_cc",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Cilindraje (cc)"
            ),
        ),
        migrations.AddField(
            model_name="vehicleitem",
            name="insurance_reports",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Reportes de aseguradora"
            ),
        ),
        migrations.AddField(
            model_name="vehicleitem",
            name="owners_count",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Cantidad de dueños"
            ),
        ),
        migrations.AddField(
            model_name="vehicleitem",
            name="steering",
            field=models.CharField(blank=True, max_length=30, verbose_name="Dirección"),
        ),
        migrations.AddField(
            model_name="vehicleitem",
            name="vehicle_category",
            field=models.CharField(
                choices=[
                    ("MOTO", "Moto"),
                    ("CAR", "Automóvil / Camioneta"),
                    ("OTHER", "Otros vehículos"),
                ],
                default="CAR",
                max_length=20,
                verbose_name="Categoría de vehículo",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Creado el"
            ),
        ),
        migrations.AlterField(
            model_name="inventoryimage",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryimage",
            name="image_url",
            field=models.URLField(max_length=500, verbose_name="URL de imagen"),
        ),
        migrations.AlterField(
            model_name="inventoryimage",
            name="is_ai_generated",
            field=models.BooleanField(default=False, verbose_name="Generada por IA"),
        ),
        migrations.AlterField(
            model_name="inventoryimage",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="inventory.inventoryitem",
                verbose_name="Publicación",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryimage",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Orden"),
        ),
        migrations.AlterField(
            model_name="inventoryimage",
            name="source_prompt",
            field=models.TextField(blank=True, verbose_name="Indicación para IA"),
        ),
        migrations.AlterField(
            model_name="inventoryimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="asset_type",
            field=models.CharField(
                choices=[("VEHICLE", "Vehículo"), ("PROPERTY", "Inmueble")],
                max_length=20,
                verbose_name="Tipo de activo",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Ciudad"),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Creado el"
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True, srid=4326, verbose_name="Ubicación"
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="price_cop",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Precio (COP)"
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Vendedor",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Disponible"),
                    ("RESERVED", "Reservado"),
                    ("SOLD", "Vendido"),
                    ("INACTIVE", "Inactivo"),
                ],
                default="AVAILABLE",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Título"),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="unlock_count",
            field=models.IntegerField(
                default=0, verbose_name="Cantidad de desbloqueos"
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="Cantidad de vistas"),
        ),
        migrations.AlterField(
            model_name="propertyitem",
            name="admin_fee_cop",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Administración (COP)",
            ),
        ),
        migrations.AlterField(
            model_name="propertyitem",
            name="area_sqm",
            field=models.IntegerField(blank=True, null=True, verbose_name="Área (m²)"),
        ),
        migrations.AlterField(
            model_name="propertyitem",
            name="available_utilities",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Servicios disponibles"
            ),
        ),
        migrations.AlterField(
            model_name="propertyitem",
            name="bathrooms",
            field=models.IntegerField(blank=True, null=True, verbose_name="Baños"),
        ),
        migrations.AlterField(
            model_name="propertyitem",
            name="bedrooms",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Habitaciones"
            ),
        ),
        migrations.AlterField(
            model_name="propertyitem",
            name="construction_year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Año de construcción"
            ),
        ),
        migrations.AlterField(
            model_name="propertyitem",
            name="floor",
            field=models.IntegerField(blank=True, null=True, verbose_name="Piso"),
        ),
        migrations.AlterField(
            model_name="propertyitem",
            name="has_elevator",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Tiene ascensor"
            ),
        ),
        migrations.AlterField(
            model_name="propertyitem",
            name="has_pool",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Tiene piscina"
            ),
        ),
        migrations.AlterField(
            model_name="propertyitem",
            name="has_social_area",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Tiene zona social"
            ),
        ),
        migrations.AlterField(
            model_name="propertyitem",
            name="has_sports_courts",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Tiene canchas deportivas"
            ),
        ),
        migrations.AlterField(
            model_name="propertyitem",
            name="has_terrace",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Tiene terraza"
            ),
        ),
        migrations.AlterField(
            model_name="propertyitem",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="property",
                serialize=False,
                to="inventory.inventoryitem",
                verbose_name="Publicación",
            ),
        ),
        migrations.AlterField(
            model_name="propertyitem",
            name="neighborhood",
            field=models.CharField(blank=True, max_length=120, verbose_name="Barrio"),
        ),
        migrations.AlterField(
            model_name="propertyitem",
            name="parking_spots",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Parqueaderos"
            ),
        ),
        migrations.AlterField(
            model_name="propertyitem",
            name="property_type",
            field=models.CharField(max_length=20, verbose_name="Tipo de inmueble"),
        ),
        migrations.AlterField(
            model_name="propertyitem",
            name="socioeconomic_stratum",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Estrato socioeconómico"
            ),
        ),
        migrations.AlterField(
            model_name="propertyitem",
            name="urbanization_type",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Tipo de urbanización"
            ),
        ),
        migrations.AlterField(
            model_name="propertyitem",
            name="utilities_avg_cop",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Promedio de servicios (COP)",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleitem",
            name="accessories",
            field=models.JSONField(blank=True, default=list, verbose_name="Accesorios"),
        ),
        migrations.AlterField(
            model_name="vehicleitem",
            name="body_type",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Tipo de carrocería"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleitem",
            name="brand",
            field=models.CharField(max_length=80, verbose_name="Marca"),
        ),
        migrations.AlterField(
            model_name="vehicleitem",
            name="doors",
            field=models.IntegerField(blank=True, null=True, verbose_name="Puertas"),
        ),
        migrations.AlterField(
            model_name="vehicleitem",
            name="fuel_type",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Tipo de combustible"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleitem",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="vehicle",
                serialize=False,
                to="inventory.inventoryitem",
                verbose_name="Publicación",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleitem",
            name="line",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Línea / versión"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleitem",
            name="mileage_km",
            field=models.IntegerField(verbose_name="Kilometraje (km)"),
        ),
        migrations.AlterField(
            model_name="vehicleitem",
            name="model",
            field=models.CharField(max_length=80, verbose_name="Modelo"),
        ),
        migrations.AlterField(
            model_name="vehicleitem",
            name="plate_last_digit",
            field=models.CharField(
                blank=True, max_length=2, verbose_name="Último dígito de placa"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleitem",
            name="single_owner",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Único dueño"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleitem",
            name="traction",
            field=models.CharField(blank=True, max_length=20, verbose_name="Tracción"),
        ),
        migrations.AlterField(
            model_name="vehicleitem",
            name="transmission",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Transmisión"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleitem",
            name="year",
            field=models.IntegerField(verbose_name="Año"),
        ),
    ]
