# Generated by Django 6.0.7 on 2026-07-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_preference_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyitem",
            name="condition",
            field=models.CharField(blank=True, max_length=20, verbose_name="Condición"),
        ),
        migrations.AddField(
            model_name="propertyitem",
            name="floors",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Número de pisos"
            ),
        ),
        migrations.AddField(
            model_name="propertyitem",
            name="furnished",
            field=models.BooleanField(blank=True, null=True, verbose_name="Amoblado"),
        ),
        migrations.AddField(
            model_name="propertyitem",
            name="listing_intent",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Arriendo / venta"
            ),
        ),
        migrations.AddField(
            model_name="propertyitem",
            name="parking_type",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Tipo de parqueadero"
            ),
        ),
        migrations.AddField(
            model_name="propertyitem",
            name="remodeling_features",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Remodelación / accesorios"
            ),
        ),
        migrations.AddField(
            model_name="propertyitem",
            name="social_amenities",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Zonas sociales"
            ),
        ),
        migrations.AddField(
            model_name="propertyitem",
            name="style",
            field=models.CharField(blank=True, max_length=40, verbose_name="Estilo"),
        ),
        migrations.AlterField(
            model_name="propertyitem",
            name="urbanization_type",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="Tipo de ubicación"
            ),
        ),
        migrations.AlterField(
            model_name="propertyitem",
            name="utilities_avg_cop",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Servicios promedio (COP)",
            ),
        ),
    ]
