# Generated by Django 6.0.7 on 2026-08-25 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_geo_location"),
        ("inventory", "0003_property_preference_matrix"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="department",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Departamento"
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="geo_city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_items",
                to="geo.geocity",
                verbose_name="Ciudad (catálogo)",
            ),
        ),
    ]
