# Generated by Django 6.0.7 on 2026-07-20 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
        ("wallet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("CONTACT_INVALID", "El contacto no existe o es inválido"),
                            ("NO_RESPONSE", "El vendedor no responde"),
                            ("ASSET_UNAVAILABLE", "El bien ya no está disponible"),
                            ("FALSE_INFO", "Información falsa o engaños"),
                            ("OTHER", "Otro motivo"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Disputa abierta"),
                            ("AUTO_REVIEW", "Verificación automática"),
                            ("HUMAN_REVIEW", "Revisión humana"),
                            ("APPROVED", "Aprobada — reembolso emitido"),
                            ("REJECTED", "Rechazada"),
                            ("APPEALED", "Apelada"),
                            ("CANCELLED", "Cancelada por el usuario"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("auto_review_started_at", models.DateTimeField(blank=True, null=True)),
                ("auto_review_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "buyer_confirmed_purchase",
                    models.BooleanField(blank=True, null=True),
                ),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                ("appeal_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "contact_unlock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes",
                        to="contacts.contactunlock",
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes_opened",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "refund_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispute_refund",
                        to="wallet.wallettransaction",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "disputes",
            },
        ),
        migrations.CreateModel(
            name="DisputeAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_url", models.URLField(max_length=500)),
                ("file_name", models.CharField(max_length=200)),
                ("mime_type", models.CharField(max_length=80)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="disputes.dispute",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispute_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dispute_attachments",
            },
        ),
        migrations.CreateModel(
            name="DisputeEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=50)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispute_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="disputes.dispute",
                    ),
                ),
            ],
            options={
                "db_table": "dispute_events",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["status", "-created_at"], name="disputes_status_1f4293_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["opened_by", "-created_at"], name="disputes_opened__a1cdf5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["auto_review_deadline"], name="disputes_auto_re_c31d70_idx"
            ),
        ),
    ]
