# Generated by Django 6.0.7 on 2026-07-20 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matching", "0001_initial"),
        ("wallet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUnlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("wantis_charged", models.IntegerField(default=1)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("PENDING", "Sin confirmar"),
                            ("PURCHASED", "Compré"),
                            ("IN_PROGRESS", "En proceso"),
                            ("NOT_PURCHASED", "No compré"),
                            ("INVALID_LEAD", "Lead inválido"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("outcome_reported_at", models.DateTimeField(blank=True, null=True)),
                ("whatsapp_opened_at", models.DateTimeField(blank=True, null=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unlocks_as_buyer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unlock",
                        to="matching.match",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unlocks_as_seller",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet_transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_unlock",
                        to="wallet.wallettransaction",
                    ),
                ),
            ],
            options={
                "db_table": "contact_unlocks",
                "indexes": [
                    models.Index(
                        fields=["buyer", "-created_at"],
                        name="contact_unl_buyer_i_fd715c_idx",
                    ),
                    models.Index(
                        fields=["seller", "-created_at"],
                        name="contact_unl_seller__7a9958_idx",
                    ),
                    models.Index(
                        fields=["outcome"], name="contact_unl_outcome_c906da_idx"
                    ),
                ],
            },
        ),
    ]
