# Generated by Django 6.0.7 on 2026-07-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverificationtoken",
            name="context",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="context",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
