# Generated by Django 6.0.7 on 2026-08-25 01:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VehicleBrand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Creado el"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "name",
                    models.CharField(max_length=80, unique=True, verbose_name="Marca"),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MOTO", "Moto"),
                            ("CAR", "Automóvil / Camioneta"),
                            ("OTHER", "Otros vehículos"),
                        ],
                        db_index=True,
                        default="CAR",
                        help_text="CAR = carros/camionetas, MOTO = motos, OTHER = otros",
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(default=False, verbose_name="Más usada"),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Marca",
                "verbose_name_plural": "Marcas",
                "db_table": "catalog_vehicle_brands",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="VehicleModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Creado el"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Modelo")),
                ("slug", models.SlugField(max_length=140)),
                (
                    "is_popular",
                    models.BooleanField(default=False, verbose_name="Más usado"),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="catalog.vehiclebrand",
                        verbose_name="Marca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo",
                "verbose_name_plural": "Modelos",
                "db_table": "catalog_vehicle_models",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="VehicleModelYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Creado el"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="Año")),
                (
                    "is_popular",
                    models.BooleanField(default=False, verbose_name="Más usado"),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="years",
                        to="catalog.vehiclemodel",
                        verbose_name="Modelo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Año de modelo",
                "verbose_name_plural": "Años de modelo",
                "db_table": "catalog_vehicle_model_years",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="VehicleVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Creado el"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Versión")),
                (
                    "catalog_key",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Clave de catálogo"
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        blank=True,
                        default="catalogo_ampliado",
                        max_length=40,
                        verbose_name="Calidad del registro",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "model_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="catalog.vehiclemodelyear",
                        verbose_name="Año",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versión",
                "verbose_name_plural": "Versiones",
                "db_table": "catalog_vehicle_versions",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="vehiclemodel",
            index=models.Index(
                fields=["brand", "is_active"], name="catalog_veh_brand_i_17347e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vehiclemodel",
            unique_together={("brand", "slug")},
        ),
        migrations.AddIndex(
            model_name="vehiclemodelyear",
            index=models.Index(
                fields=["model", "year"], name="catalog_veh_model_i_503c2a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vehiclemodelyear",
            unique_together={("model", "year")},
        ),
        migrations.AddIndex(
            model_name="vehicleversion",
            index=models.Index(
                fields=["model_year", "is_active"],
                name="catalog_veh_model_y_20ef41_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vehicleversion",
            unique_together={("model_year", "name")},
        ),
    ]
