# Generated by Django 6.0.7 on 2026-08-25 03:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleVersionSpec",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Creado el"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "fuel_types",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Combustibles permitidos"
                    ),
                ),
                (
                    "transmissions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Transmisiones permitidas",
                    ),
                ),
                (
                    "tractions",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Tracciones permitidas"
                    ),
                ),
                (
                    "body_types",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Carrocerías permitidas"
                    ),
                ),
                (
                    "engine_cc",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Cilindraje de referencia (cc)",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="inferred",
                        help_text="inferred | manual | import",
                        max_length=40,
                        verbose_name="Origen",
                    ),
                ),
                (
                    "version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="catalog.vehicleversion",
                        verbose_name="Versión",
                    ),
                ),
            ],
            options={
                "verbose_name": "Specs de versión",
                "verbose_name_plural": "Specs de versiones",
                "db_table": "catalog_vehicle_version_specs",
            },
        ),
    ]
