# Generated by Django 6.0.7 on 2026-08-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_version_specs_and_trade_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclebrand",
            name="category",
            field=models.CharField(
                choices=[
                    ("CAR", "Carros"),
                    ("SUV", "Camionetas"),
                    ("MOTO", "Motos"),
                    ("COLLECTION", "Carros de colección"),
                    ("TRUCK", "Camiones"),
                    ("NAUTICAL", "Náutica"),
                    ("HEAVY_MACHINERY", "Maquinaria pesada"),
                    ("OTHER", "Otros vehículos"),
                ],
                db_index=True,
                default="CAR",
                help_text="Categoría de vehículo asociada a la marca en el catálogo",
                max_length=20,
                verbose_name="Categoría",
            ),
        ),
        migrations.AlterField(
            model_name="vehiclebrand",
            name="name",
            field=models.CharField(max_length=80, verbose_name="Marca"),
        ),
        migrations.AddConstraint(
            model_name="vehiclebrand",
            constraint=models.UniqueConstraint(
                fields=("name", "category"), name="unique_brand_name_per_category"
            ),
        ),
    ]
