# Generated by Django 6.0.7 on 2026-07-20 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("needs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.IntegerField()),
                ("distance_km", models.DecimalField(decimal_places=2, max_digits=6)),
                ("required_criteria_met", models.BooleanField(default=True)),
                ("unmet_preferences", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GENERATED", "Generado"),
                            ("VIEWED", "Visto por el comprador"),
                            ("UNLOCKED", "Contacto desbloqueado"),
                            ("DISCARDED", "Descartado"),
                        ],
                        default="GENERATED",
                        max_length=20,
                    ),
                ),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                ("unlocked_at", models.DateTimeField(blank=True, null=True)),
                ("discarded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches_as_buyer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "need",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="needs.need",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches_as_seller",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "matches",
            },
        ),
        migrations.CreateModel(
            name="MatchCriterionResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attribute", models.CharField(max_length=80)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("REQUIRED", "Obligatorio"),
                            ("PREFERRED", "Preferencia"),
                        ],
                        max_length=20,
                    ),
                ),
                ("expected_value", models.CharField(max_length=150)),
                ("actual_value", models.CharField(max_length=150)),
                ("met", models.BooleanField()),
                ("contribution", models.IntegerField()),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria_results",
                        to="matching.match",
                    ),
                ),
            ],
            options={
                "db_table": "match_criterion_results",
            },
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["buyer", "status"], name="matches_buyer_i_7828cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["seller", "status"], name="matches_seller__33948b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["need", "-score"], name="matches_need_id_9dc2cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["score"], name="matches_score_aa87f8_idx"),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.UniqueConstraint(
                fields=("need", "inventory_item"), name="unique_match_per_pair"
            ),
        ),
        migrations.AddIndex(
            model_name="matchcriterionresult",
            index=models.Index(
                fields=["match", "met"], name="match_crite_match_i_22dd3c_idx"
            ),
        ),
    ]
