# Generated by Django 6.0.7 on 2026-07-20 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TopupPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("wantis_base", models.IntegerField()),
                ("wantis_bonus", models.IntegerField(default=0)),
                ("price_cop", models.DecimalField(decimal_places=2, max_digits=15)),
                ("is_popular", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "topup_packages",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("balance_wantis", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wallets",
            },
        ),
        migrations.CreateModel(
            name="TopupOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("wantis_total", models.IntegerField()),
                ("price_cop", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("COMPLETED", "Completada"),
                            ("FAILED", "Fallida"),
                            ("REFUNDED", "Reembolsada"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "provider_reference",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("provider_payload", models.JSONField(blank=True, default=dict)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="topup_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="wallet.topuppackage",
                    ),
                ),
            ],
            options={
                "db_table": "topup_orders",
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="topup_order_user_id_8fd689_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="topup_order_status_e8fb7e_idx",
                    ),
                    models.Index(
                        fields=["provider_reference"],
                        name="topup_order_provide_034202_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("TOPUP", "Recarga"),
                            ("BONUS", "Bonificación por volumen"),
                            ("UNLOCK", "Desbloqueo de contacto"),
                            ("REFUND", "Reembolso por disputa"),
                            ("ADJUSTMENT", "Ajuste administrativo"),
                            ("REWARD", "Recompensa por calificar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount_wantis", models.IntegerField()),
                ("balance_after", models.IntegerField()),
                ("related_object_type", models.CharField(blank=True, max_length=50)),
                ("related_object_id", models.UUIDField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallet_transactions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "wallet_transactions",
                "indexes": [
                    models.Index(
                        fields=["wallet", "-created_at"],
                        name="wallet_tran_wallet__3d47ad_idx",
                    ),
                    models.Index(
                        fields=["transaction_type"],
                        name="wallet_tran_transac_377ecc_idx",
                    ),
                ],
            },
        ),
    ]
