# Generated by Django 6.0.7 on 2026-08-25 02:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeoDepartment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Creado el"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Departamento"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Código DANE"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "db_table": "geo_departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GeoCity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Creado el"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="Ciudad / municipio"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitud",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitud",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "is_capital",
                    models.BooleanField(
                        default=False, verbose_name="Capital de departamento"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="geo.geodepartment",
                        verbose_name="Departamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ciudad / municipio",
                "verbose_name_plural": "Ciudades / municipios",
                "db_table": "geo_cities",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["department", "is_active"],
                        name="geo_cities_departm_401b2a_idx",
                    ),
                    models.Index(fields=["name"], name="geo_cities_name_6359af_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("department", "name"), name="unique_city_per_department"
                    )
                ],
            },
        ),
    ]
