# Generated by Django 6.0.7 on 2026-07-20 20:40

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Need",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("VEHICLE", "Vehículo"), ("PROPERTY", "Inmueble")],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "budget_max_cop",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("CASH", "Contado"),
                            ("CREDIT", "Crédito"),
                            ("TRADE_IN", "Permuta"),
                        ],
                        max_length=20,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("ACTIVE", "Activa"),
                            ("PAUSED", "Pausada"),
                            ("EXPIRED", "Expirada"),
                            ("FULFILLED", "Cumplida"),
                            ("DELETED", "Eliminada"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("matches_count", models.IntegerField(default=0)),
                ("views_count", models.IntegerField(default=0)),
                (
                    "legal_disclaimer_accepted_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="needs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "needs",
            },
        ),
        migrations.CreateModel(
            name="PropertyNeed",
            fields=[
                (
                    "need",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="property",
                        serialize=False,
                        to="needs.need",
                    ),
                ),
                ("property_type", models.CharField(max_length=20)),
                ("neighborhood", models.CharField(blank=True, max_length=120)),
                ("area_min_sqm", models.IntegerField(blank=True, null=True)),
                ("bedrooms_min", models.IntegerField(blank=True, null=True)),
                ("bathrooms_min", models.IntegerField(blank=True, null=True)),
                ("parking_spots_min", models.IntegerField(blank=True, null=True)),
                ("has_elevator", models.BooleanField(blank=True, null=True)),
                ("urbanization_type", models.CharField(blank=True, max_length=30)),
                ("has_pool", models.BooleanField(blank=True, null=True)),
                ("has_sports_courts", models.BooleanField(blank=True, null=True)),
                ("has_social_area", models.BooleanField(blank=True, null=True)),
                ("has_terrace", models.BooleanField(blank=True, null=True)),
                (
                    "max_construction_age_years",
                    models.IntegerField(blank=True, null=True),
                ),
                ("socioeconomic_stratum", models.IntegerField(blank=True, null=True)),
                (
                    "admin_fee_max_cop",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "utilities_max_cop",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("required_utilities", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "need_properties",
            },
        ),
        migrations.CreateModel(
            name="VehicleNeed",
            fields=[
                (
                    "need",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="vehicle",
                        serialize=False,
                        to="needs.need",
                    ),
                ),
                ("brand", models.CharField(max_length=80)),
                ("model", models.CharField(max_length=80)),
                ("line", models.CharField(blank=True, max_length=120)),
                ("year_min", models.IntegerField(blank=True, null=True)),
                ("year_max", models.IntegerField(blank=True, null=True)),
                ("fuel_type", models.CharField(blank=True, max_length=30)),
                ("body_type", models.CharField(blank=True, max_length=30)),
                ("mileage_max_km", models.IntegerField(blank=True, null=True)),
                ("traction", models.CharField(blank=True, max_length=10)),
                ("transmission", models.CharField(blank=True, max_length=20)),
                ("doors", models.IntegerField(blank=True, null=True)),
                ("single_owner", models.BooleanField(blank=True, null=True)),
                ("plate_last_digit", models.CharField(blank=True, max_length=20)),
                ("accessories", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "need_vehicles",
            },
        ),
        migrations.CreateModel(
            name="NeedCriterion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attribute", models.CharField(max_length=80)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("REQUIRED", "Obligatorio"),
                            ("PREFERRED", "Preferencia"),
                        ],
                        max_length=20,
                    ),
                ),
                ("weight", models.IntegerField(default=10)),
                (
                    "need",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="needs.need",
                    ),
                ),
            ],
            options={
                "db_table": "need_criteria",
            },
        ),
        migrations.CreateModel(
            name="NeedImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image_url", models.URLField(max_length=500)),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("order", models.IntegerField(default=0)),
                (
                    "need",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="needs.need",
                    ),
                ),
            ],
            options={
                "db_table": "need_images",
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="need",
            index=models.Index(
                fields=["buyer", "status"], name="needs_buyer_i_005af3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="need",
            index=models.Index(
                fields=["asset_type", "status"], name="needs_asset_t_f2db5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="need",
            index=models.Index(fields=["expires_at"], name="needs_expires_edab72_idx"),
        ),
        migrations.AddIndex(
            model_name="need",
            index=models.Index(fields=["city"], name="needs_city_29c6a0_idx"),
        ),
        migrations.AddIndex(
            model_name="needcriterion",
            index=models.Index(
                fields=["need", "mode"], name="need_criter_need_id_c13750_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="needcriterion",
            constraint=models.UniqueConstraint(
                fields=("need", "attribute"), name="unique_criterion_per_need"
            ),
        ),
    ]
