# Generated by Django 6.0.7 on 2026-07-24 03:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("needs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="need",
            options={"verbose_name": "Necesidad", "verbose_name_plural": "Necesidades"},
        ),
        migrations.AlterModelOptions(
            name="needcriterion",
            options={
                "verbose_name": "Criterio de necesidad",
                "verbose_name_plural": "Criterios de necesidad",
            },
        ),
        migrations.AlterModelOptions(
            name="needimage",
            options={
                "ordering": ["order"],
                "verbose_name": "Imagen de necesidad",
                "verbose_name_plural": "Imágenes de necesidad",
            },
        ),
        migrations.AlterModelOptions(
            name="propertyneed",
            options={
                "verbose_name": "Necesidad de inmueble",
                "verbose_name_plural": "Necesidades de inmueble",
            },
        ),
        migrations.AlterModelOptions(
            name="vehicleneed",
            options={
                "verbose_name": "Necesidad de vehículo",
                "verbose_name_plural": "Necesidades de vehículo",
            },
        ),
        migrations.AddField(
            model_name="need",
            name="payment_types",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Tipos de pago aceptados"
            ),
        ),
        migrations.AddField(
            model_name="need",
            name="trade_in_description",
            field=models.TextField(
                blank=True, verbose_name="Descripción de la permuta"
            ),
        ),
        migrations.AddField(
            model_name="vehicleneed",
            name="color",
            field=models.CharField(blank=True, max_length=40, verbose_name="Color"),
        ),
        migrations.AddField(
            model_name="vehicleneed",
            name="engine_cc",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Cilindraje (cc)"
            ),
        ),
        migrations.AddField(
            model_name="vehicleneed",
            name="insurance_reports",
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name="Reportes de aseguradora aceptados",
            ),
        ),
        migrations.AddField(
            model_name="vehicleneed",
            name="owners_max",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Dueños máximos aceptados"
            ),
        ),
        migrations.AddField(
            model_name="vehicleneed",
            name="steering",
            field=models.CharField(blank=True, max_length=30, verbose_name="Dirección"),
        ),
        migrations.AddField(
            model_name="vehicleneed",
            name="vehicle_category",
            field=models.CharField(
                choices=[
                    ("MOTO", "Moto"),
                    ("CAR", "Automóvil / Camioneta"),
                    ("OTHER", "Otros vehículos"),
                ],
                default="CAR",
                max_length=20,
                verbose_name="Categoría de vehículo",
            ),
        ),
        migrations.AlterField(
            model_name="need",
            name="asset_type",
            field=models.CharField(
                choices=[("VEHICLE", "Vehículo"), ("PROPERTY", "Inmueble")],
                max_length=20,
                verbose_name="Tipo de activo",
            ),
        ),
        migrations.AlterField(
            model_name="need",
            name="budget_max_cop",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Presupuesto máximo (COP)"
            ),
        ),
        migrations.AlterField(
            model_name="need",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="needs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Comprador",
            ),
        ),
        migrations.AlterField(
            model_name="need",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Ciudad"),
        ),
        migrations.AlterField(
            model_name="need",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Creado el"
            ),
        ),
        migrations.AlterField(
            model_name="need",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="need",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Expira el"),
        ),
        migrations.AlterField(
            model_name="need",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="need",
            name="legal_disclaimer_accepted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Aviso legal aceptado el"
            ),
        ),
        migrations.AlterField(
            model_name="need",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True, srid=4326, verbose_name="Ubicación"
            ),
        ),
        migrations.AlterField(
            model_name="need",
            name="matches_count",
            field=models.IntegerField(
                default=0, verbose_name="Cantidad de coincidencias"
            ),
        ),
        migrations.AlterField(
            model_name="need",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("CASH", "Efectivo"),
                    ("TRANSFER", "Transferencia"),
                    ("CREDIT", "Crédito bancario"),
                    ("TRADE_IN", "Permuta"),
                ],
                max_length=20,
                verbose_name="Tipo de pago principal",
            ),
        ),
        migrations.AlterField(
            model_name="need",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Borrador"),
                    ("ACTIVE", "Activa"),
                    ("PAUSED", "Pausada"),
                    ("EXPIRED", "Expirada"),
                    ("FULFILLED", "Cumplida"),
                    ("DELETED", "Eliminada"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="need",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Título"),
        ),
        migrations.AlterField(
            model_name="need",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
        ),
        migrations.AlterField(
            model_name="need",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="Cantidad de vistas"),
        ),
        migrations.AlterField(
            model_name="needcriterion",
            name="attribute",
            field=models.CharField(max_length=80, verbose_name="Atributo"),
        ),
        migrations.AlterField(
            model_name="needcriterion",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Creado el"
            ),
        ),
        migrations.AlterField(
            model_name="needcriterion",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="needcriterion",
            name="mode",
            field=models.CharField(
                choices=[("REQUIRED", "Obligatorio"), ("PREFERRED", "Preferencia")],
                max_length=20,
                verbose_name="Modo",
            ),
        ),
        migrations.AlterField(
            model_name="needcriterion",
            name="need",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="criteria",
                to="needs.need",
                verbose_name="Necesidad",
            ),
        ),
        migrations.AlterField(
            model_name="needcriterion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
        ),
        migrations.AlterField(
            model_name="needcriterion",
            name="weight",
            field=models.IntegerField(default=10, verbose_name="Peso"),
        ),
        migrations.AlterField(
            model_name="needimage",
            name="caption",
            field=models.CharField(blank=True, max_length=200, verbose_name="Leyenda"),
        ),
        migrations.AlterField(
            model_name="needimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Creado el"
            ),
        ),
        migrations.AlterField(
            model_name="needimage",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="needimage",
            name="image_url",
            field=models.URLField(max_length=500, verbose_name="URL de imagen"),
        ),
        migrations.AlterField(
            model_name="needimage",
            name="need",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="needs.need",
                verbose_name="Necesidad",
            ),
        ),
        migrations.AlterField(
            model_name="needimage",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Orden"),
        ),
        migrations.AlterField(
            model_name="needimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
        ),
        migrations.AlterField(
            model_name="propertyneed",
            name="admin_fee_max_cop",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Administración máxima (COP)",
            ),
        ),
        migrations.AlterField(
            model_name="propertyneed",
            name="area_min_sqm",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Área mínima (m²)"
            ),
        ),
        migrations.AlterField(
            model_name="propertyneed",
            name="bathrooms_min",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Baños mínimos"
            ),
        ),
        migrations.AlterField(
            model_name="propertyneed",
            name="bedrooms_min",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Habitaciones mínimas"
            ),
        ),
        migrations.AlterField(
            model_name="propertyneed",
            name="has_elevator",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Tiene ascensor"
            ),
        ),
        migrations.AlterField(
            model_name="propertyneed",
            name="has_pool",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Tiene piscina"
            ),
        ),
        migrations.AlterField(
            model_name="propertyneed",
            name="has_social_area",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Tiene zona social"
            ),
        ),
        migrations.AlterField(
            model_name="propertyneed",
            name="has_sports_courts",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Tiene canchas deportivas"
            ),
        ),
        migrations.AlterField(
            model_name="propertyneed",
            name="has_terrace",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Tiene terraza"
            ),
        ),
        migrations.AlterField(
            model_name="propertyneed",
            name="max_construction_age_years",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Antigüedad máxima de construcción (años)",
            ),
        ),
        migrations.AlterField(
            model_name="propertyneed",
            name="need",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="property",
                serialize=False,
                to="needs.need",
                verbose_name="Necesidad",
            ),
        ),
        migrations.AlterField(
            model_name="propertyneed",
            name="neighborhood",
            field=models.CharField(blank=True, max_length=120, verbose_name="Barrio"),
        ),
        migrations.AlterField(
            model_name="propertyneed",
            name="parking_spots_min",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Parqueaderos mínimos"
            ),
        ),
        migrations.AlterField(
            model_name="propertyneed",
            name="property_type",
            field=models.CharField(max_length=20, verbose_name="Tipo de inmueble"),
        ),
        migrations.AlterField(
            model_name="propertyneed",
            name="required_utilities",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Servicios requeridos"
            ),
        ),
        migrations.AlterField(
            model_name="propertyneed",
            name="socioeconomic_stratum",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Estrato socioeconómico"
            ),
        ),
        migrations.AlterField(
            model_name="propertyneed",
            name="urbanization_type",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Tipo de urbanización"
            ),
        ),
        migrations.AlterField(
            model_name="propertyneed",
            name="utilities_max_cop",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Servicios máximos (COP)",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleneed",
            name="accessories",
            field=models.JSONField(blank=True, default=list, verbose_name="Accesorios"),
        ),
        migrations.AlterField(
            model_name="vehicleneed",
            name="body_type",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Tipo de carrocería"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleneed",
            name="brand",
            field=models.CharField(max_length=80, verbose_name="Marca"),
        ),
        migrations.AlterField(
            model_name="vehicleneed",
            name="doors",
            field=models.IntegerField(blank=True, null=True, verbose_name="Puertas"),
        ),
        migrations.AlterField(
            model_name="vehicleneed",
            name="fuel_type",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Tipo de combustible"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleneed",
            name="line",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Línea / versión"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleneed",
            name="mileage_max_km",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Kilometraje máximo (km)"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleneed",
            name="model",
            field=models.CharField(max_length=80, verbose_name="Modelo"),
        ),
        migrations.AlterField(
            model_name="vehicleneed",
            name="need",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="vehicle",
                serialize=False,
                to="needs.need",
                verbose_name="Necesidad",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleneed",
            name="plate_last_digit",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Último dígito de placa"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleneed",
            name="single_owner",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Único dueño"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleneed",
            name="traction",
            field=models.CharField(blank=True, max_length=20, verbose_name="Tracción"),
        ),
        migrations.AlterField(
            model_name="vehicleneed",
            name="transmission",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Transmisión"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleneed",
            name="year_max",
            field=models.IntegerField(blank=True, null=True, verbose_name="Año máximo"),
        ),
        migrations.AlterField(
            model_name="vehicleneed",
            name="year_min",
            field=models.IntegerField(blank=True, null=True, verbose_name="Año mínimo"),
        ),
    ]
