# Generated by Django 6.0.7 on 2026-07-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("needs", "0002_preference_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyneed",
            name="condition",
            field=models.CharField(blank=True, max_length=20, verbose_name="Condición"),
        ),
        migrations.AddField(
            model_name="propertyneed",
            name="floors_min",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Número de pisos mínimo"
            ),
        ),
        migrations.AddField(
            model_name="propertyneed",
            name="furnished",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Amoblado"
            ),
        ),
        migrations.AddField(
            model_name="propertyneed",
            name="listing_intent",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Arriendo / venta"
            ),
        ),
        migrations.AddField(
            model_name="propertyneed",
            name="parking_type",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Tipo de parqueadero"
            ),
        ),
        migrations.AddField(
            model_name="propertyneed",
            name="remodeling_features",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Remodelación / accesorios"
            ),
        ),
        migrations.AddField(
            model_name="propertyneed",
            name="social_amenities",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Zonas sociales"
            ),
        ),
        migrations.AddField(
            model_name="propertyneed",
            name="style",
            field=models.CharField(blank=True, max_length=40, verbose_name="Estilo"),
        ),
        migrations.AlterField(
            model_name="need",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("CASH", "Efectivo"),
                    ("TRANSFER", "Transferencia"),
                    ("CREDIT", "Crédito"),
                    ("MORTGAGE", "Crédito hipotecario"),
                    ("TRADE_IN", "Permuta"),
                ],
                max_length=20,
                verbose_name="Tipo de pago principal",
            ),
        ),
        migrations.AlterField(
            model_name="propertyneed",
            name="has_elevator",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Ascensor"
            ),
        ),
        migrations.AlterField(
            model_name="propertyneed",
            name="neighborhood",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Barrio / ubicación"
            ),
        ),
        migrations.AlterField(
            model_name="propertyneed",
            name="urbanization_type",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="Tipo de ubicación"
            ),
        ),
    ]
