# Generated by Django 6.0.7 on 2026-07-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("needs", "0003_property_preference_matrix"),
    ]

    operations = [
        migrations.AddField(
            model_name="need",
            name="renewal_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Recordatorio de renovación enviado el",
            ),
        ),
    ]
