# Generated by Django 6.0.7 on 2026-08-25 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_geo_location"),
        ("needs", "0004_renewal_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="need",
            name="department",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Departamento"
            ),
        ),
        migrations.AddField(
            model_name="need",
            name="geo_city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="needs",
                to="geo.geocity",
                verbose_name="Ciudad (catálogo)",
            ),
        ),
        migrations.AddField(
            model_name="need",
            name="travel_cities",
            field=models.ManyToManyField(
                blank=True,
                related_name="needs_as_travel",
                to="geo.geocity",
                verbose_name="Ciudades de desplazamiento",
            ),
        ),
        migrations.AddField(
            model_name="need",
            name="willing_to_travel",
            field=models.BooleanField(
                default=False, verbose_name="Dispuesto a desplazarse a otras ciudades"
            ),
        ),
    ]
