# Generated by Django 6.0.7 on 2026-08-25 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_geo_location"),
        ("needs", "0005_geo_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="need",
            name="trade_in_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="needs_as_trade_in",
                to="inventory.inventoryitem",
                verbose_name="Inventario ofrecido en permuta",
            ),
        ),
    ]
